name: UrlChecker

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: URLs-checker
      uses: urlstechie/urlchecker-action@0.2.1
      with:
        subfolder: src/pages
        file_types: .md, .mdx
